apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts/'
    targetRevision: 58.5.3
    chart: kube-prometheus-stack
    helm:
      valueFiles:
        - https://github.com/cybera/rSOC-Kube-Apps/MonitoringValues/values.yaml
  sources: []
  project: default
  syncPolicy:
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
